export const data = [
  {
    main_question: "Alcohol",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "lifestyle",
    sub_ques: [
      {
        main_question: "Substance Consumed",
        question_description: null,
        response_type: "dropdown",
        value: "",
        question_type: "lifestyle",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
        options: [
          { label: "Hard Liquor", value: "Hard Liquor" },
          { label: "Beer", value: "Beer" },
          { label: "Wine", value: "Wine" },
        ],
        multi_select: false,
      },
      {
        main_question: "Diagnosis Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Quantity(in ml)",
        question_description: "",
        response_type: "number",
        value: "",
        question_type: "lifestyle",
        sub_ques: [],
        question_for: ["self", "spouse", "son", "daughter", "mother", "father"],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
  {
    main_question: "Has planned a surgery ?",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "medical",
    sub_ques: [
      {
        main_question: "Exact Diagnosis",
        question_description: null,
        response_type: "bool",
        value: "",
        question_type: "medical",
        sub_ques: [
          {
            main_question: "Diagnosis Date",
            question_description: null,
            response_type: "bool",
            value: "",
            question_type: "medical",
            sub_ques: [
              {
                main_question: "Consultation Date",
                question_description: null,
                response_type: "date",
                value: "",
                question_type: "medical",
                sub_ques: [],
                question_for: [],
                is_mandatory: 1,
              },
            ],
            question_for: [],
            is_mandatory: 1,
          },
        ],
        question_for: [],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
  {
    main_question: "Takes medicines regularly ?",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "medical",
    sub_ques: [
      {
        main_question: "Exact Diagnosis",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Diagnosis Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Consultation Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Medicine Name",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
  {
    main_question: "Has been advised investigation or further tests ?",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "medical",
    sub_ques: [
      {
        main_question: "Date Of Test",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Type Of Test",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Finding Of Test",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
  {
    main_question: "Was hospitalized in past?",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "medical",
    sub_ques: [
      {
        main_question: "Exact Diagnosis",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Diagnosis Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Consultation Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Hospital Name",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
      {
        main_question: "Details Of Past Medical Condition",
        question_description: null,
        response_type: "text",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
  {
    main_question: "Is expecting a baby ?",
    question_description: null,
    response_type: "bool",
    value: "",
    question_type: "medical",
    sub_ques: [
      {
        main_question: "Expected Delivery Date",
        question_description: null,
        response_type: "date",
        value: "",
        question_type: "medical",
        sub_ques: [],
        question_for: [],
        is_mandatory: 1,
      },
    ],
    question_for: [],
    is_mandatory: 1,
  },
];
